# Generated by Django 3.2.18 on 2023-03-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_hist_ind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind', models.SmallIntegerField(default=0)),
                ('title', models.CharField(max_length=70)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='bks/list', verbose_name='Основное изображение')),
            ],
        ),
        migrations.AlterField(
            model_name='hist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bks/list', verbose_name='Основное изображение'),
        ),
    ]
